---
deployment:
  tasks:
    - export DEPLOYPATH=/home/miaotoke/repositories/miao-official-page
    - cd $DEPLOYPATH
    - /bin/rm -rf .next
    - /bin/npm install
    - export NODE_ENV=production
    - /bin/npm run build
    - /bin/chmod -R 755 .next
    - /bin/chmod -R 755 public