---
deployment:
  tasks:
    - export DEPLOYPATH=/home/miaotoke/repositories/miao-official-page
    - cd $DEPLOYPATH
    - /bin/pwd
    - /bin/test -f package.json
    - /bin/npm install
    - /bin/test -d .next || (export NODE_ENV=production && export NODE_OPTIONS="--max-old-space-size=1024" && export NEXT_TELEMETRY_DISABLED=1 && /bin/npm run build || echo "Build falhou - use BUILD_LOCAL.md para fazer build local")
    - /bin/test -d .next
    - /bin/test -f .next/BUILD_ID
    - /bin/chmod -R 755 .next
    - /bin/chmod -R 755 public