---
deployment:
  tasks:
    - /bin/rm -rf .next node_modules/.cache .swc
    - /bin/npm ci || /bin/npm install
    - /bin/npm run build
    - /bin/chmod -R 755 .next
    - /bin/chmod -R 755 public
    - /bin/mkdir -p logs
    - /bin/chmod 755 logs